- name: Install epel repository
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Install fail2ban packages
  yum:
    name: "{{ fail2ban_packages }}"
    state: present
    update_cache: yes
  with_items: "{{ fail2ban_packages }}"

- name: Copy fail2ban conf
  copy:
    src: "{{ fail2ban_conf }}"
    dest: "{{ fail2ban_local }}"
    remote_src: yes

- name: Ignore localhost ip
  lineinfile:
    path: "{{ fail2ban_local }}"
    regexp: '^#ignoreip'
    line: "ignoreip = 127.0.0.1/8"
    state: present

- name: Create sshd.local file
  file:
    path: "{{ sshd_local_file }}"
    state: touch

- name: Copy content to sshd.local file
  blockinfile:
    dest: "{{ sshd_local_file }}"
    marker: "#{mark} FAIL2BAN : ANSIBLE MANAGED BLOCK"
    state: present
    backup: yes
    block: |
      {{ sshd_local_content }}

- name: Start and enable fail2ban service
  systemd:
    name: fail2ban
    state: started
    enabled: yes

- name: Start and enable firewalld service
  systemd:
    name: firewalld
    state: started
    enabled: yes

